### ISSUE TITLE
Updating the charm icon

### ISSUE THREAD

**Issue by kwm14** [panagiotisl/bigtop#5]
The design team at Canonical would like to update charm icons to fit within the new circular format, as displayed in the current GUI.

This will improve how charms are displayed in the store, search results and on charm details pages.

I've attached a new version of the charm icon. If you're happy with this change, please could you update the icon and let us know when it's done.

[girafe.svg.zip](https://github.com/panagiotisl/bigtop/files/1172900/girafe.svg.zip)

Thanks

**Comment by panagiotisl** [comment]
Hi Karl, I just did and pushed the change to my master branch. Should I request a pull from bigtop?

**Comment by kwm14** [comment]
Hi Panagiotis, yes please.

Thanks, Karl

**Comment by panagiotisl** [comment]
Closing this as I just requested a pull, thank you for your help Karl!
