### ISSUE TITLE
latest giraph candidate charm seems outdated

### ISSUE THREAD

**Issue by kwmonroe** [panagiotisl/bigtop#6]
Hey @panagiotisl, I was taking a look at the latest candidate charm in the store:

https://jujucharms.com/giraph/2

It doesn't seem to have the latest updates from your master branch, including the new icon and readme updates from:

https://github.com/panagiotisl/bigtop/issues/5
https://github.com/panagiotisl/bigtop/pull/4

Would you please rebuild/push/release a new candidate?  For reference, the steps are as follows:

```
$ cd <location-of-your-forked-bigtop-master-branch>
$ cd bigtop-packages/src/charm/giraph/layer-giraph
$ charm build -r --no-local-layers --series xenial
...
build: Destination charm directory: /home/ubuntu/charms/xenial/giraph
...
$ cd /home/ubuntu/charms/xenial/giraph
$ charm proof
$ charm push `pwd` ~panagiotisl/giraph
...
<charmstore url>
...
$ charm release --channel candidate cs:~panagiotisl/giraph-<#>
```

Once a new candidate is available in the store, I'll merge your code upstream and close this JIRA:

https://issues.apache.org/jira/browse/BIGTOP-2875

Please let me know if you have any questions/concerns with this. Thanks!!

**Comment by panagiotisl** [comment]
Hi @kwmonroe 
Thanks for all the help, I was waiting for a review of cs:~panagiotisl/giraph-9 but if my understanding is correct the review queue is now history.

I followed the steps you kindly provided me with but I am having trouble releasing the charm:

```
$ charm release --channel candidate cs:~panagiotisl/giraph-10
ERROR cannot release charm or bundle: resources are missing from publish request: bigtop-repo
$ charm release --channel candidate cs:~panagiotisl/giraph-10 --resource bigtop-repo
error: invalid value "bigtop-repo" for flag --resource: invalid revision number
```
Any ideas?

**Comment by kwmonroe** [comment]
Gah!  I'm sorry @panagiotisl, I forgot that all bigtop charms now include a resource for the bigtop source code.  I made this change to the bigtop base layer to support people deploying charms in restricted networks (where things like "git clone ..." don't work):

https://github.com/juju-solutions/layer-apache-bigtop-base/pull/58

With this change, all bigtop charms now need to have a resource defined and pushed to the store.  The steps for this are:

```
$ wget https://github.com/apache/bigtop/archive/branch-1.2.zip -O /tmp/branch-1.2.zip
$ cd /home/ubuntu/charms/xenial/giraph
$ charm proof
$ charm push `pwd` ~panagiotisl/giraph --resource bigtop-repo=/tmp/branch-1.2.zip
...
<charmstore url revision-X>
<resource bigtop-repo-Y>
...
$ charm release --channel candidate cs:~panagiotisl/giraph-<X> --resource bigtop-repo-<Y>
```

After this point, you can omit the wget and resource definition during `charm push`.  You would simply release new revs of the giraph charm with the existing bigtop-repo resource, e.g.:

```
$ <new stuff>
$ charm push `pwd` ~panagiotisl/giraph
$ charm release --channel candidate cs:~panagiotisl/giraph-<X++> --resource bigtop-repo-1
```

Of course, when a new version of bigtop is released, you'll want to update the resource associated with it.  At that point, you'd wget a new source and push your charm with it.  Then you'd have a new revision of the resource, as in `bigtop-repo-2`.

I hope that makes sense, but please let me know if you have any questions.  I'll write this up in a more detailed blog post for others that are contributing to the bigtop charms.  Thanks for the patience and effort in getting giraph updated!!

**Comment by panagiotisl** [comment]
Thanks @kwmonroe 
I followed your instructions and it looks like the charm is updated successfully! I am closing the issue, let me know if something is still wrong.
